[model]
context_len = 168
pred_len = 24
vocab_size = 8192
num_encoder_layers = 12
num_decoder_layers = 12
d_model = 768
nhead = 12
dim_feedforward = 2048
dropout = 0.0
activation = 'gelu'
continuous_loads = false
ignore_spatial = false

[pretrain]
batch_size = 256
init_scale = 0.02
warmup_steps = 10000
lr = 0.00006
scheduler_steps = 162760
tokenizer_without_merge = true

[zero_shot]
tokenizer_without_merge = true