[model]
context_len = 168
pred_len = 24
vocab_size = 3747
num_encoder_layers = 12
num_decoder_layers = 12
d_model = 768
nhead = 12
dim_feedforward = 2048
dropout = 0.0
activation = 'gelu'
continuous_loads = false
ignore_spatial = true

[pretrain]
batch_size = 64
init_scale = 0.02
warmup_steps = 10000
lr = 0.00006
train_tokens = 1000000000
tokenizer_without_merge = false

[zero_shot]
tokenizer_without_merge = false
