[model]
context_len = 168
pred_len = 24
num_encoder_layers = 2
num_decoder_layers = 2
nhead = 4
dim_feedforward = 512
d_model = 256
dropout = 0.0
activation = 'gelu'
continuous_loads = true
ignore_spatial = false
continuous_head = 'gaussian_nll'

[pretrain]
batch_size = 128
init_scale = 0.02
warmup_steps = 10000
lr = 0.0006
train_tokens = 1000000000
apply_scaler_transform = 'boxcox'
weather = ['all']

[zero_shot]
apply_scaler_transform = 'boxcox'
weather = ['all']

[transfer_learning]
apply_scaler_transform = 'boxcox'
weather = ['all']